version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "GH Action Dep"
      include: "scope"
    groups:
      actions-deps:
        patterns:
          - "*"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily" 
    labels:
      - "dependencies" 
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    commit-message:
      prefix: "Poetry Dep"
      include: "scope"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
