name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
        with:
          python-version: "3.x"

      - name: Ensure tag is v-prefixed
        id: check_tag
        run: |
          if [[ "${{ github.ref }}" != refs/tags/v* ]]; then
            echo "Error: Release tag must be v-prefixed (e.g., v1.0.0)."
            exit 1
          fi

      - name: Extract version from release tag
        id: get_version
        run: |
          echo "Release tag: ${{ github.event.release.tag_name }}"
          VERSION="${{ github.event.release.tag_name }}"
          VERSION="${VERSION#v}"
          echo "Version: $VERSION"
          echo "release_version=$VERSION" >> $GITHUB_ENV

      - name: Install Poetry
        run: pipx install poetry==1.8.4

      - name: Update version in pyproject.toml
        run: |
          poetry version ${{ env.release_version }}

      - name: Build release distributions
        run: |
          poetry build

      - name: Upload distributions
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest

    needs:
      - release-build

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    # Dedicated environments with protections for publishing are strongly recommended.
    environment:
      name: pypi
      # OPTIONAL: uncomment and update to include your PyPI project URL in the deployment status:
      url: https://pypi.org/project/graphedexcel/

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # release/v1
